# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.1.1 on 2026-10-06 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0046_organiser_organiser_slug_lower_unique"),
        ("submission", "0112_submission_submission_code_upper_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreGeneration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("seq", models.PositiveBigIntegerField()),
                ("status", models.CharField(default="pending", max_length=16)),
                ("cursor_position", models.PositiveBigIntegerField(default=0)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_generations",
                        to="event.event",
                    ),
                ),
            ],
            options={"ordering": ("seq",)},
        ),
        migrations.CreateModel(
            name="ReviewScoreCandidate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("review_updated", models.DateTimeField(blank=True, null=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_candidates",
                        to="submission.review",
                    ),
                ),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="submission.scoregeneration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScoreGenerationCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("source_category_id", models.BigIntegerField()),
                (
                    "weight",
                    models.DecimalField(decimal_places=1, default=1, max_digits=4),
                ),
                ("active", models.BooleanField(default=True)),
                ("is_independent", models.BooleanField(default=False)),
                ("track_ids", models.JSONField(default=list)),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frozen_categories",
                        to="submission.scoregeneration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScoreGenerationOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("source_score_id", models.BigIntegerField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="submission.scoregenerationcategory",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="scoregeneration",
            index=models.Index(
                fields=["event", "status"], name="submission__event_i_8ae455_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scoregeneration", unique_together={("event", "seq")}
        ),
        migrations.AddIndex(
            model_name="reviewscorecandidate",
            index=models.Index(
                fields=["generation", "review_updated"],
                name="submission__generat_afc21b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reviewscorecandidate", unique_together={("generation", "review")}
        ),
        migrations.AlterUniqueTogether(
            name="scoregenerationcategory",
            unique_together={("generation", "source_category_id")},
        ),
        migrations.AlterUniqueTogether(
            name="scoregenerationoption",
            unique_together={("category", "source_score_id")},
        ),
    ]
